export default {
  LOADING: 'LOADING',
  LOADED: 'LOADED',

  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_ERROR: 'SET_ERROR',

  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  SET_TITLE: 'SET_TITLE'
}
